article/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "article"

urlpatterns = [
    path('dashboard/',views.dashboard,name = "dashboard"),
    path('addarticle/',views.addarticle,name = "addarticle"),
    path('article/<int:id>',views.detail,name = "detail"),
    path('update/<int:id>',views.updateArticle,name = "update"),
    path('delete/<int:id>',views.deleteArticle,name = "delete"),
    path('',views.articles,name = "articles"),
    path('comment/<int:id>',views.addComment,name = "comment"),
]

blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


from article import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name = "index"),
    path('about/',views.about,name = "about"),
    path('articles/',include("article.urls")),
    path('user/',include("user.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.

class Article(models.Model):
    author = models.ForeignKey("auth.User", on_delete = models.CASCADE,verbose_name = "Yazar")
    title = models.CharField(max_length= 50, verbose_name="Başlık")
    content = RichTextField()
    created_date = models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma Tarihi")
    article_image = models.FileField(blank=True,null = True, verbose_name="Add Photo on Article")
    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['-created_date']
 
class Comment(models.Model):
    article = models.ForeignKey(Article,on_delete = models.CASCADE, verbose_name = "Add Comment",related_name="comments")
    comment_author = models.CharField(max_length=50,verbose_name="Name")
    comment_content = models.CharField(max_length=200,verbose_name="Comment content")
    comment_date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.comment_content
    class Meta:
        ordering = ['-comment_date']

article/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title","content","article_image"]
        

article/views.py
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404,reverse
from .forms import ArticleForm
from .models import Article,Comment
from django.contrib import messages
from django.contrib.auth.decorators import login_required


# Create your views here.
"""
def index(request):
    #return HttpResponse("Anasayfa") // <h3> Anasayfa </h3>
    context = {
        "numbers": [1,2,3,4,5]
    }
    return render(request,"index.html",context)
"""
#Dynamic URL
#def detail(request,id):
#    return HttpResponse("Detail:" + str(id))

def articles(request):
    keyword = request.GET.get("keyword")

    if keyword:
        articles = Article.objects.filter(title__contains = keyword)
        return render(request,"articles.html",{"articles":articles})

    articles = Article.objects.all()
    return render(request,"articles.html",{"articles":articles})

def index(request):
    return render(request,"index.html")

def about(request):
    return render(request,"about.html")

@login_required(login_url = "user:login")
def dashboard(request):
    articles = Article.objects.filter(author = request.user)
    context = {
        "articles": articles
    }

    return render(request,"dashboard.html",context)
@login_required(login_url = "user:login")
def addarticle(request):
    form = ArticleForm(request.POST or None,request.FILES or None)

    if form.is_valid():
        article = form.save(commit=False) #dont save, I will implement myself
        article.author = request.user
        article.save()

        """
        article object
        you should define author here.
        article.save()
        """
        messages.success(request,"Article is successfully added!")
        return redirect("article:dashboard")

    return render(request,"addarticle.html",{"form":form})


def detail(request,id):
    #article = Article.objects.filter(id = id).first()
    article = get_object_or_404(Article,id = id)

    comments = article.comments.all()

    return render(request,"detail.html",{"article":article,"comments":comments})

@login_required(login_url = "user:login")
def updateArticle(request,id):
    article = get_object_or_404(Article,id = id)
    form = ArticleForm(request.POST or None,request.FILES or None,instance=article)
    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()

        messages.success(request,"Article is successfully updated!")
        return redirect("article:dashboard")

    return render(request,"update.html",{"form":form})

@login_required(login_url = "user:login")
def deleteArticle(request,id):
    article = get_object_or_404(Article,id = id)
    article.delete()
    messages.success(request,"Article is successfully deleted!")
    return redirect("article:dashboard")

def addComment(request,id):
    article = get_object_or_404(Article,id = id)

    if request.method == "POST":
        comment_author = request.POST.get("comment_author")
        comment_content = request.POST.get("comment_content")

        newComment = Comment(comment_author= comment_author, comment_content= comment_content)
        newComment.article = article
        newComment.save()
    return redirect(reverse("article:detail",kwargs={"id":id}))
    #/articles/detail/15 -> when we are redirecting dynamic URL






    

templates/about.html
{% extends "layout.html" %}

 {% block body  %}
    <div style="font-family: Arial, Helvetica, sans-serif;font-weight: bold;">
    <h3> About the Project </h3>
    <hr>
    
    <p>
    This project is mainly built for sharing articles/notes between people.<br>
    Users have chances to Add, Update and Delete operations.
    In order to use "CemBYT", you have to Register to the system(if you don't have account yet). <br>
    CemBYT is a panel which supports session control, this means that you cannot use some functionalities without logging in.
    For example, seeing control panel, adding/updating/deleting operations and controlling your articles.<br>
    <br> IN THE LEFT SIDE, you will see
    <br> -CemBYT!
    <br> -About
    <br> -Articles<br>
    
    <br> In CemBYT!, you may see the Introduction and the UML Diagram of the Project, also lovely PJATK logo :)
    <br>
    
    <br> IN THE RIGHT SIDE, you will see
    <br> -Register Panel
    <br> -Login Panel<br>
    <br>
    After logging in, when you click "Control Panel", you will see Share Article button, in this way, you will add a new article.
    If you don't have any article yet, you will see "You don't have any article yet" message.
   </p>
   <p>
    Creating Article:
    <br>
    - Title
    <br>
    - Content (Supported by CKEditor)
    <br>
    - Add Photo on Article
    </p>
    <p>
    In Control Panel you may see your individual articles(In Form format):
    <br>
    (When you add a new Article you will see Article is successly added! message), you will see
    <br>-id
    <br>-Title
    <br>-Author
    <br>-Date
    <br>-Update Button(You can ONLY update your own Article)
    <br>-> Update Panel will be shown when you click.(Data will be persistent)
    <br>-Delete Button(You can ONLY delete your own Article)
    <br><br/>
    <img style="border:5px solid black;" src="../media/PJATK-NAUKA.png" alt="pja">
    <br>
    <br>
    All your articles will be published in "Articles", here is a place where all articles are put.
    <br> You may click "Continue Read" if you want to read all.
    <br> You may Search Articles on the top.
    <br> All articles list will be shown with title, author information and created date information.
    <br> You may click title of Article in order to see the details.
    <br>
    When you click an Article, you may also make a comment!
    <br>
    All articles will be sorted by newest from the system automatically.
    <br>
    Furthermore, Admin Panel is automatically created by Django Web Framework, operations also can be achieved by ../admin.
    IF YOU ARE ADMIN...
    </p>
    <hr>
    <div>
    <div>
      <i>Chosen Technologies</i><br>
      <br>	Python 3.7
      <br>	Django 2.1.5 Web Framework
      <br>	DbSqlite3 (Default Database for Django Web Framework)
      <br>	HTML5, CSS3, JavaScript, BootStrap 4.3.1, JQuery 3.2.1
      <br>	CKEditor
      <br>	Django ORM
      <br>	Django Crispy Forms
      <br>	Django Cleanup
      <br>	Google Code Prettify
    </div>
    <hr>
    <div style="float:right">
    Created by<i style="color:red"> Samet Cem Habiboglu - s17181 </i>
    <div>

 {% endblock  %}    

templates/addarticle.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}
    
    
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h3> Create Article </h3>
            <hr>
        
        <form method="post" enctype="multipart/form-data"> 
        {% csrf_token %}
        {{form.media}}
        {{form|crispy}}
        <br>
        <button type="submit" class="btn btn-primary"> Create </button>

        </form>
        
        
        
        
        
        
        </div>
    </div>

{% endblock body %}

templates/articles.html
{% extends "layout.html" %}

{% block body %}
    <div class="row">
        <div class="col-md-10 offset-md-0">
            <h3> Articles </h3>
                <hr>
        </div>
    </div>
    <div class ="row">
    <div class="col-md-10 offset-md-8">
        <div class="col-lg-8">
            <form>
                 {% csrf_token %} 
                <input type="text" name = "keyword" class="input-sm" maxlength="64" placeholder="Search...">
              <button type="submit" class="btn btn-warning">Search</button>
            </form>
      </div>
    </div>

</div>

    {% if articles %}
        {% for article in articles %}
        <div class="row">
        <div class="col-md-10 offset-md-2">

        <!-- Post Content Column -->
        <div class="col-lg-8">

        <!-- Title -->
        <a href="{% url 'article:detail' article.id %}"><h2 class="mt-2">{{article.title}}</h2></a>
        <!-- Dynamic Url -->
        <!-- Author -->
        <p class="lead">
            Published by <strong> {{article.author.username}}</strong></a>
        </p>
        <hr>

        <!-- Date/Time -->
        <p>Posted on {{article.created_date}}</p>

        <hr>

        <!-- Preview Image -->
        {% if article.article_image %}
        <!-- Non Dynamic Url (both are okey) -->
        <a href="/articles/article/{{article.id}}"><img class="img-fluid rounded" src="{{article.article_image.url}}" alt=""></a>
        <hr>
        {% endif %}

        <!-- Post Content -->
        <p class="lead"> {{article.content | safe | truncatewords:30}} </p>
        
        <a style="float: right" href="/articles/article/{{article.id}}" class="btn btn-danger"> Continue Read </a>
        <br/><br>
        <hr>
                </div>
            </div>
        </div>
        
        {% endfor %}




    {% else %}
        <div class ="row">
            <div class="col-md-10 offset-md-0">
                <div class="col-lg-8">
                    <div class = "alert alert-danger">
                        There is no article in this BLOG!
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

{% endblock body %}

templates/dashboard.html
{% extends "layout.html" %}

{% block body %}
    <h3> Control Panel </h3>
    <hr>
    <p> Welcome, <strong> {{request.user.username}}! </strong></p>
    <a class="btn btn-danger" href="/articles/addarticle"> Share Article</a>
    <hr>


    {% if articles %}
        <table class="table table-striped table-dark">
        <thead>
    <tr>
      <th scope="col">#id</th>
      <th scope="col">Title</th>
      <th scope="col">Author</th>
      <th scope="col">Date</th>
      <th scope="col">Update</th>
      <th scope="col">Delete</th>
    </tr>
        </thead>
        <tbody>

    {% for article in articles  %}
      <tr>
        <th scope="row">{{article.id}}</th>
        <td><a href="/articles/article/{{article.id}}">{{article.title}}</a></td>
        <td>{{article.author.username}}</td>
        <td>{{article.created_date}}</td>
        <td><a href="/articles/update/{{article.id}}" class="btn btn-primary"> Update </a></td>
        <td><a href="/articles/delete/{{article.id}}" class="btn btn-danger"> Delete </a></td>
    </tr>
    {% endfor %}
    
        </tbody>
    </table>
    
    {% else %}
        <div class="alert alert-danger">
            You don't have any article yet...
        </div>
    {% endif %}
    {% endblock body %}






    

templates/detail.html
{% extends "layout.html" %}

{% block body %}
     <div class="row">

      <!-- Post Content Column -->
      <div class="col-lg-8">

        <!-- Title -->
        <h2 class="mt-4">{{article.title}}</h2>

        <!-- Author -->
        <p class="lead">
          Published by {{article.author.username}} on {{article.created_date}}</a>
        </p>
        <hr>

        <!-- Date/Time -->
        <p>Posted on {{article.created_date}}</p>

        <hr>

        <!-- Preview Image -->
        {% if article.article_image %}
        <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="">
        <hr>
        {% endif %}

        <!-- Post Content -->
        <p class="lead"> {{article.content | safe}} </p>



        <hr>

      <h4>Comments</h4>
      <hr>
      {% if comments %}
      {% for comment in comments  %}
        <div class="media mb-4">
          <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
          <div class="media-body">
            <h5 class="mt-0">{{comment.comment_author}}</h5>
            {{comment.comment_date}} <br>
            {{comment.comment_content}}
          </div>
        </div>
      {% endfor %}
      
      
      {% else %}
      <div class ="alert alert-danger">
        There is no comment in this article yet! Do it first!
      </div>
      {% endif %}
      <br>

      <div class="card my-4">
          <h5 class="card-header">Add Comment:</h5>
          <div class="card-body">
            <form method = "post" action = "{% url 'article:comment' article.id %}">
              {% csrf_token %}
              <div class="form-group">
                  <label for="formGroupExampleInput">Name</label>
                  <input name = "comment_author" type="text" class="form-control" id="formGroupExampleInput" placeholder="Input your name">
                </div>
              <div class="form-group">
                  <label for="formGroupExampleInput">Comment</label>
                <textarea name = "comment_content" class="form-control" rows="3"></textarea>
              </div>
              <button type="submit" class="btn btn-danger">Add</button>
            </form>
          </div>
        </div>
        </div>
      </div>

{% endblock body %}

templates/index.html
{% extends "layout.html" %}

{% block body %}
      <p>
        {% if request.user.is_authenticated %}
                <strong>Logged in, Welcome <i style="color:red"> {{request.user.username}}</i>!</strong>
                <hr>
        {% else %}
                <h3 style="Arial Black, Gadget, sans-serif;"><i> Please Log In</i>  </h3>
                <hr>
        {% endif %}


    </p>
    <div class = "jumbotron text-center">
        <h3 style="color:red"> Welcome to the BYT Project of Samet Cem Habiboglu(s17181)</h3>
        <p><b> In cemBYT, you will have fun and you will be able to share your articles with people!</b></p>
        <p><u> You may look the UML Diagram of the project below! </u></p>
        <img  style="border:5px solid black" src="media/UML_diagram_s17181.png" alt="uml">
        <br></br>
        <br></br>
        <img  style="border:5px solid black" src="media/pjatk.png" alt="uml">
    </div>
  

  
    
{% endblock  %} 

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
    <title>cemBYT Project!</title>
</head>
<body>
    {% include "includes/navbar.html" %}

  
    <div style="margin-top: 100px; margin-bottom:100px" class="container">
      {% if messages %}
      {% for message in messages %}

      {% if message.tags == "info"%}
         <div class="alert alert-danger">{{ message }}</div>
      {% else %}
         <div class="alert alert-{{ message.tags }}">{{ message }}</div>
      {% endif %}
      {% endfor %}
      {% endif %}

        {% block body %}
        
        {% endblock body %}
    </div>

    <script src="{% static 'js/bootstrap.min.js'%}"></script>
    <script src="{% static 'js/jquery-3.2.1.min.js '%}"></script>
    <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>
</body>
</html>

templates/login.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}
    
    
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h3> Logging In </h3>
            <hr>
        
        <form method="post"> 
        {% csrf_token %}
        {{form|crispy}}
        <br>
        <button type="submit" class="btn btn-primary"> Log In </button>

        </form>
        
        
        
        
        
        
        </div>
    </div>
    

{% endblock body %}
    

templates/register.html
{% extends "layout.html" %}

{% block body %}
    {% load crispy_forms_tags %}
    
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h3> Registering </h3>
            <hr>
        
        <form method="post"> 
        {% csrf_token %}
        {{form| crispy}}
        <br>
        <button type="submit" class="btn btn-primary"> Register </button>

        </form>
        </div>
    </div>

{% endblock body %}

templates/update.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}
    
    
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h3> Update Article </h3>
            <hr>
        
        <form method="post" enctype="multipart/form-data"> 
        {% csrf_token %}
        {{form.media}}
        {{form|crispy}}
        <br>
        <button type="submit" class="btn btn-primary"> Update </button>

        </form>
        
        
        
        
        
        
        </div>
    </div>

{% endblock body %}